### ISSUE TITLE
Japitana's files

### ISSUE THREAD

**Issue by Cainday-Bradley** [PUP-BSIT/ex9-avengears#9]
𝟖𝟎 𝐂𝐨𝐥𝐮𝐦𝐧𝐬 𝐢𝐬𝐬𝐮𝐞

https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/japitana_johnwalter/index.html#L10

Edit Suggestion:
```
<link
      href="https://fonts.googleapis.com/css2?family=Tac+One&display=swap"
      rel="stylesheet"
 />
```
    
I also see a 80 columns issue in your CSS file but it's not that much a problem since it's a link, but you can enhance the readability of it.

https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/japitana_johnwalter/style.css#L26

Edit Suggestion: 

```
@font-face {
  font-family: "ProggySquareTT";
  src: url("https://db.onlinewebfonts.com/t/5423e3f6b569eee8bb7179f1319240ea.eot");
  src: url("https://db.onlinewebfonts.com/t/5423e3f6b569eee8bb7179f1319240ea.eot?#iefix")
      format("embedded-opentype"),
    url("https://db.onlinewebfonts.com/t/5423e3f6b569eee8bb7179f1319240ea.woff2")
      format("woff2"),
    url("https://db.onlinewebfonts.com/t/5423e3f6b569eee8bb7179f1319240ea.woff")
      format("woff"),
    url("https://db.onlinewebfonts.com/t/5423e3f6b569eee8bb7179f1319240ea.ttf")
      format("truetype"),
    url("https://db.onlinewebfonts.com/t/5423e3f6b569eee8bb7179f1319240ea.svg#ProggySquareTT")
      format("svg");
}
```

I also see some excess/unnecessary indentation, so I recommend for you to install a prettier extension, this may help you with the proper format of your HTML and CSS file.
Please see this link for your guide: https://www.freecodecamp.org/news/how-to-use-prettier-in-visual-studio-code/

**Comment by Cainday-Bradley** [comment]
𝐔𝐬𝐞 𝐚 𝐥𝐨𝐰𝐞𝐫𝐜𝐚𝐬𝐞 𝐰𝐢𝐭𝐡 𝐧𝐚𝐦𝐢𝐧𝐠 𝐲𝐨𝐮𝐫 𝐜𝐥𝐚𝐬𝐬 𝐚𝐧𝐝 𝐝𝐨 𝐚 𝐝𝐞𝐬𝐜𝐫𝐢𝐩𝐭𝐢𝐯𝐞 𝐧𝐚𝐦𝐞 𝐭𝐨 𝐢𝐭 𝐟𝐨𝐫 𝐫𝐞𝐚𝐝𝐚𝐛𝐢𝐥𝐢𝐭𝐲 𝐩𝐮𝐫𝐩𝐨𝐬𝐞𝐬.

https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/japitana_johnwalter/index.html#L31

https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/japitana_johnwalter/index.html#L73

For example: 
```
<div class="exercise-7">
<div class="exercise-8">
```

**Comment by Villa-VillaDiana** [comment]
> 𝐔𝐬𝐞 𝐚 𝐥𝐨𝐰𝐞𝐫𝐜𝐚𝐬𝐞 𝐰𝐢𝐭𝐡 𝐧𝐚𝐦𝐢𝐧𝐠 𝐲𝐨𝐮𝐫 𝐜𝐥𝐚𝐬𝐬 𝐚𝐧𝐝 𝐝𝐨 𝐚 𝐝𝐞𝐬𝐜𝐫𝐢𝐩𝐭𝐢𝐯𝐞 𝐧𝐚𝐦𝐞 𝐭𝐨 𝐢𝐭 𝐟𝐨𝐫 𝐫𝐞𝐚𝐝𝐚𝐛𝐢𝐥𝐢𝐭𝐲 𝐩𝐮𝐫𝐩𝐨𝐬𝐞𝐬.
> 
> https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/japitana_johnwalter/index.html#L31
> 
> https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/japitana_johnwalter/index.html#L73
> 
> For example:
> 
> ```
> <div class="exercise-7">
> <div class="exercise-8">
> ```

In addition to this issue, please consider using a descriptive class name. This will be beneficial for you all in the future.

e.g. Instead of
`<div class="class-2">` 
You may say
`<div class="works">`
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/japitana_johnwalter/index.html#L32
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/japitana_johnwalter/index.html#L45
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/japitana_johnwalter/index.html#L63
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/japitana_johnwalter/index.html#L76
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/japitana_johnwalter/index.html#L80
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/japitana_johnwalter/index.html#L84
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/japitana_johnwalter/index.html#L88
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/japitana_johnwalter/index.html#L93
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/japitana_johnwalter/index.html#L98
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/japitana_johnwalter/index.html#L102

**Comment by Villa-VillaDiana** [comment]
Instead of placing the img:hover at the end of your code, you might want to position it right after your img selector. It is good practice to have your related codes/elements in sequence. This will be beneficial in the future as your codes become longer.

https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/japitana_johnwalter/style.css#L106-L114
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/japitana_johnwalter/style.css#L216-L218

**Comment by Villa-VillaDiana** [comment]
Since you've set EEEEEE as the color of all your text, it also affects the color of input. To solve this issue, you may want to add a separate style for input so that the text will be visible.
`input {
  color: black;
}`

![image](https://github.com/PUP-BSIT/ex9-avengears/assets/146617812/14ab54ae-93bf-4dc9-a407-08e384e1b6aa)

**Comment by Japitana-JohnWalter** [comment]
thank you
